### ISSUE TITLE
error event just contains record name?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#125]
```
ds.on('error', error =>
  console.log(`Deepstream Error ${error}.`)
)
```

Will print: 

```
Deepstream Error file/4.
```

However, if I remove the error handler:

```
--- You can catch all deepstream errors by subscribing to the error event ---
2016-05-27T15:36:14.773Z - error: uncaughtException: UNSOLICITED_MESSAGE: file/5 (R)
{ date: 'Fri May 27 2016 17:36:14 GMT+0200 (CEST)',
  process:
   { pid: 10116,
     uid: 501,
     gid: 20,
     cwd: '/Users/ronagy/Projects/GitHub/nxtedition/nxt-media',
     execPath: '/Users/ronagy/.nvm/versions/node/v5.5.0/bin/node',
     version: 'v5.5.0',
     argv:
      [ '/Users/ronagy/.nvm/versions/node/v5.5.0/bin/node',
        '/Users/ronagy/Projects/GitHub/nxtedition/nxt-media/src' ],
     memoryUsage: { rss: 117547008, heapTotal: 93375264, heapUsed: 50938592 } },
  os:
   { loadavg: [ 1.9248046875, 1.82568359375, 1.810546875 ],
     uptime: 284312 },
  trace:
   [ { column: 9,
       file: '/Users/ronagy/Projects/GitHub/nxtedition/nxt-media/node_modules/deepstream.io-client-js/src/client.js',
       function: '[object Object].Client._$onError',
       line: 186,
       method: 'Client._$onError',
       native: false },
     { column: 16,
       file: '/Users/ronagy/Projects/GitHub/nxtedition/nxt-media/node_modules/deepstream.io-client-js/src/record/record-handler.js',
       function: '[object Object].RecordHandler._$handle',
       line: 234,
       method: 'RecordHandler._$handle',
       native: false },
     { column: 42,
       file: '/Users/ronagy/Projects/GitHub/nxtedition/nxt-media/node_modules/deepstream.io-client-js/src/client.js',
       function: '[object Object].Client._$onMessage',
       line: 129,
       method: 'Client._$onMessage',
       native: false },
     { column: 17,
       file: '/Users/ronagy/Projects/GitHub/nxtedition/nxt-media/node_modules/deepstream.io-client-js/src/message/connection.js',
       function: '[object Object].Connection._onMessage',
       line: 314,
       method: 'Connection._onMessage',
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 90,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: '[object Object].emit',
       line: 182,
       method: 'emit',
       native: false },
     { column: 7,
       file: '/Users/ronagy/Projects/GitHub/nxtedition/nxt-media/node_modules/deepstream.io-client-js/src/tcp/tcp-connection.js',
       function: '[object Object].TcpConnection._onData',
       line: 180,
       method: 'TcpConnection._onData',
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 90,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 182,
       method: 'emit',
       native: false },
     { column: 16,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 147,
       method: null,
       native: false } ],
  stack:
   [ 'Error: UNSOLICITED_MESSAGE: file/5 (R)',
     '    at [object Object].Client._$onError (/Users/ronagy/Projects/GitHub/nxtedition/nxt-media/node_modules/deepstream.io-client-js/src/client.js:186:9)',
     '    at [object Object].RecordHandler._$handle (/Users/ronagy/Projects/GitHub/nxtedition/nxt-media/node_modules/deepstream.io-client-js/src/record/record-handler.js:234:16)',
     '    at [object Object].Client._$onMessage (/Users/ronagy/Projects/GitHub/nxtedition/nxt-media/node_modules/deepstream.io-client-js/src/client.js:129:42)',
     '    at [object Object].Connection._onMessage (/Users/ronagy/Projects/GitHub/nxtedition/nxt-media/node_modules/deepstream.io-client-js/src/message/connection.js:314:17)',
     '    at emitOne (events.js:90:13)',
     '    at [object Object].emit (events.js:182:7)',
     '    at [object Object].TcpConnection._onData (/Users/ronagy/Projects/GitHub/nxtedition/nxt-media/node_modules/deepstream.io-client-js/src/tcp/tcp-connection.js:180:7)',
     '    at emitOne (events.js:90:13)',
     '    at Socket.emit (events.js:182:7)',
     '    at readableAddChunk (_stream_readable.js:147:16)' ] }
```

**Comment by WolframHempel** [comment]
Error is called with three arguments - but your method only uses one. Try
```javascript
ds.on('error', ( error, event, topic ) =>
  console.log(error, event, topic);
)
```

**Comment by ronag** [comment]
@WolframHempel: Thanks! However, that's a bit unclear from the documentation, https://www.deepstream.io/docs/client.html

**Comment by yasserf** [comment]
Good point! Raised issue on website accordingly.
