### ISSUE TITLE
Cannot read property '_$onMessage' of undefined

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#167]
```javascript
/deepstream.io-client-js/src/record/record-handler.js:276
	var onMessage = this._records[ recordName ]._$onMessage.bind( this._records[ recordName ] );
	                                           ^

TypeError: Cannot read property '_$onMessage' of undefined
    at RecordHandler._onDestroyPending (foo/node_modules/deepstream.io-client-js/src/record/record-handler.js:276:45)
    at Emitter.emit (foo/node_modules/component-emitter/index.js:134:20)
    at .<anonymous> (foo/node_modules/deepstream.io-client-js/src/record/record.js:236:9)
    at on (foo/node_modules/component-emitter/index.js:66:8)
    at Emitter.emit (foo/node_modules/component-emitter/index.js:134:20)
    at Record._setReady (foo/node_modules/deepstream.io-client-js/src/record/record.js:455:7)
    at Record._onRead (foo/node_modules/deepstream.io-client-js/src/record/record.js:439:7)
    at Record._$onMessage (foo/node_modules/deepstream.io-client-js/src/record/record.js:289:9)
    at RecordHandler._$handle (foo/node_modules/deepstream.io-client-js/src/record/record-handler.js:228:25)
    at Client._$onMessage (foo/node_modules/deepstream.io-client-js/src/client.js:130:42)
```
```

**Comment by ronag** [comment]
Seems to happen during reconnection:

```javascript
16:13:51.368Z  INFO foo:  (connectionState=ERROR)
16:13:51.369Z  INFO foo: Deepstream Connection State Changed. (connectionState=RECONNECTING)
16:13:51.369Z  INFO foo:  (connectionState=RECONNECTING)
16:13:51.371Z  INFO foo: Deepstream Error. (event=connectionError, topic=null)
  error: Can't connect! Deepstream server unreachable on 0.0.0.0:6021
16:13:55.375Z  INFO foo: Deepstream Connection State Changed. (connectionState=AWAITING_CONNECTION)
16:13:55.375Z  INFO foo:  (connectionState=AWAITING_CONNECTION)
16:13:55.376Z  INFO foo: Deepstream Connection State Changed. (connectionState=AWAITING_AUTHENTICATION)
16:13:55.376Z  INFO foo:  (connectionState=AWAITING_AUTHENTICATION)
16:13:55.376Z  INFO foo: Deepstream Connection State Changed. (connectionState=AUTHENTICATING)
16:13:55.376Z  INFO foo:  (connectionState=AUTHENTICATING)
16:13:55.377Z  INFO foo: Deepstream Connection State Changed. (connectionState=OPEN)
16:13:55.377Z  INFO foo:  (connectionState=OPEN)
16:13:55.505Z  INFO foo:  (key=search/simple?{"query":"","count":128}, isSubscribed=true)
16:13:55.506Z  INFO foo:  (key=search/simple?{"query":"","count":256}, isSubscribed=true)
foo/node_modules/deepstream.io-client-js/src/record/record-handler.js:276
	var onMessage = this._records[ recordName ]._$onMessage.bind( this._records[ recordName ] );
	                                           ^

TypeError: Cannot read property '_$onMessage' of undefined
    at RecordHandler._onDestroyPending (foo/node_modules/deepstream.io-client-js/src/record/record-handler.js:276:45)
    at Emitter.emit (foo/node_modules/component-emitter/index.js:134:20)
    at .<anonymous> (foo/node_modules/deepstream.io-client-js/src/record/record.js:236:9)
    at on (foo/node_modules/component-emitter/index.js:66:8)
    at Emitter.emit (foo/node_modules/component-emitter/index.js:134:20)
    at Record._setReady (foo/node_modules/deepstream.io-client-js/src/record/record.js:455:7)
    at Record._onRead (foo/node_modules/deepstream.io-client-js/src/record/record.js:439:7)
    at Record._$onMessage (foo/node_modules/deepstream.io-client-js/src/record/record.js:289:9)
    at RecordHandler._$handle (foo/node_modules/deepstream.io-client-js/src/record/record-handler.js:228:25)
    at Client._$onMessage (foo/node_modules/deepstream.io-client-js/src/client.js:130:42)
```

**Comment by ronag** [comment]
Here is a reproducible example:

```javascript
import deepstream from 'deepstream.io-client-js'

const ds = deepstream('0.0.0.0:6021')
  .login({}, (success, authData) => {
    if (!success) {
      console.log({ authData }, 'Deepstream Authentication Failed. Shutting down...')
      setTimeout(() => process.exit(1), 500)
    }
  })

ds.on('connectionStateChanged', connectionState => {
  console.log({ connectionState }, 'Deepstream Connection State Changed.')
})

ds.on('error', (error, event, topic) => {
  console.log({ error, event, topic }, 'Deepstream Error.')
})

setInterval(() => {
  for (let n = 0; n < 8; ++n) {
    updateRecord()
  }
}, 500)

let x = 0
function updateRecord () {
  const record = ds.record.getRecord('test/1')
  record.set({ x })
  record.discard()
  x++
}
```

```
{ connectionState: 'OPEN' } 'Deepstream Connection State Changed.'
/Users/ronagy/Projects/GitHub/public/ds-playground/node_modules/deepstream.io-client-js/src/record/record-handler.js:276
	var onMessage = this._records[ recordName ]._$onMessage.bind( this._records[ recordName ] );
	                                           ^

TypeError: Cannot read property '_$onMessage' of undefined
    at RecordHandler._onDestroyPending (/Users/ronagy/Projects/GitHub/public/ds-playground/node_modules/deepstream.io-client-js/src/record/record-handler.js:276:45)
    at Emitter.emit (/Users/ronagy/Projects/GitHub/public/ds-playground/node_modules/component-emitter/index.js:134:20)
    at .<anonymous> (/Users/ronagy/Projects/GitHub/public/ds-playground/node_modules/deepstream.io-client-js/src/record/record.js:233:9)
    at on (/Users/ronagy/Projects/GitHub/public/ds-playground/node_modules/component-emitter/index.js:66:8)
    at Emitter.emit (/Users/ronagy/Projects/GitHub/public/ds-playground/node_modules/component-emitter/index.js:134:20)
    at Record._setReady (/Users/ronagy/Projects/GitHub/public/ds-playground/node_modules/deepstream.io-client-js/src/record/record.js:452:7)
    at Record._onRead (/Users/ronagy/Projects/GitHub/public/ds-playground/node_modules/deepstream.io-client-js/src/record/record.js:436:7)
    at Record._$onMessage (/Users/ronagy/Projects/GitHub/public/ds-playground/node_modules/deepstream.io-client-js/src/record/record.js:286:9)
    at RecordHandler._$handle (/Users/ronagy/Projects/GitHub/public/ds-playground/node_modules/deepstream.io-client-js/src/record/record-handler.js:228:25)
    at Client._$onMessage (/Users/ronagy/Projects/GitHub/public/ds-playground/node_modules/deepstream.io-client-js/src/client.js:128:42)
```

**Comment by yasserf** [comment]
Great, thank you!

**Comment by ronag** [comment]
Any progress on this issue? It's starting to become a bit more urgent for us...

**Comment by yasserf** [comment]
We got this issue and the other two you just commented on put in for the next release, aiming for friday/monday.

**Comment by timaschew** [comment]
The issue it's fixed in a branch, missing some tests.
For now you can use a more defensive implementation to avoid the issue:

```javascript
'use strict'
const deepstream = require('.')
const Promise = require('bluebird')

const ds = deepstream('0.0.0.0:6021')
  .login({}, (success, authData) => {
    if (!success) {
      console.log({ authData }, 'Deepstream Authentication Failed. Shutting down...')
      setTimeout(() => process.exit(1), 500)
    }
  })

ds.on('connectionStateChanged', connectionState => {
  console.log({ connectionState }, 'Deepstream Connection State Changed.')
})

ds.on('error', (error, event, topic) => {
  console.log({ error, event, topic }, 'Deepstream Error.')
})

setInterval(Promise.coroutine(function*() {
  for (let n = 0; n < 8; ++n) {
    yield updateRecord()
  }
}), 500)

let x = 0
function updateRecord () {
  console.log(x)
  return new Promise((resolve, reject) => {
    const record = ds.record.getRecord('test/1')
    record.set({ x: x++ })
    record.on( 'discard', () => {
      resolve()
    })
    record.discard()
  })
}
```

There is a related issue, when you use `record.delete()`.
Even if you use the same defensive way this is the result:

```
0
1
{ error: 'test/1', event: 'MULTIPLE_SUBSCRIPTIONS', topic: 'R' } 'Deepstream Error.'
2
{ error: 'test/1', event: 'MULTIPLE_SUBSCRIPTIONS', topic: 'R' } 'Deepstream Error.'
3
{ error: 'test/1', event: 'MULTIPLE_SUBSCRIPTIONS', topic: 'R' } 'Deepstream Error.'
```
