### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#178]
Could probably be handled more gracefully:

```javascript
Unexpected end of JSON input
    at Object.parse (native)
    at Record._onRead (/node_modules/deepstream.io-client-js/src/record/record.js:437:21)
    at Record._$onMessage (/node_modules/deepstream.io-client-js/src/record/record.js:289:9)
    at RecordHandler._$handle (/node_modules/deepstream.io-client-js/src/record/record-handler.js:228:25)
    at Client._$onMessage (/node_modules/deepstream.io-client-js/src/client.js:128:42)
    at Connection._onMessage (/node_modules/deepstream.io-client-js/src/message/connection.js:322:17)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at TcpConnection._onData (/node_modules/deepstream.io-client-js/src/tcp/tcp-connection.js:180:7)
    at emitOne (events.js:96:13)
```

**Comment by yasserf** [comment]
Question is more around how you managed to receive corrupt data under the 'O' data type which means it should be data.

This is tightly related to the other issue:

https://github.com/deepstreamIO/deepstream.io/issues/285

**Comment by ronag** [comment]
@yasserf: You are right. Though I think it would be nice if we had more invariant checks for certain assumptions, e.g. a connector should always return an object otherwise it should be an error or warning?

**Comment by ronag** [comment]
@yasserf: Actually I just updated the connector and cleared the database but I still get the error?

**Comment by yasserf** [comment]
The data is likely still in the cache

**Comment by ronag** [comment]
That packet logger would be nice :)

**Comment by ronag** [comment]
Still problem after killing and restarting everything:
```
h59ec2765:test ronagy$ docker-compose down
Stopping test_elasticsearch_1 ... done
Stopping test_redis_1 ... done
Stopping test_rethinkdb_1 ... done
Removing test_elasticsearch_1 ... done
Removing test_redis_1 ... done
Removing test_rethinkdb_1 ... done
Removing network test_default
h59ec2765:test ronagy$ docker-compose up -d
Creating network "test_default" with the default driver
Creating test_elasticsearch_1
Creating test_rethinkdb_1
Creating test_redis_1
```

**Comment by ronag** [comment]
Here is the server log:

```
10:36:39.319Z  INFO server: logger ready (event=INFO)
10:36:39.341Z  INFO server: deepstream version: 1.0.0 (event=INFO)
10:36:39.342Z  INFO server: authenticationHandler ready (event=INFO)
10:36:39.342Z  INFO server: permissionHandler ready (event=INFO)
10:36:39.354Z  INFO server: cache ready (event=INFO)
10:36:39.355Z  INFO server: messageConnector ready (event=INFO)
10:36:39.364Z  INFO server: storage ready (event=INFO)
10:36:39.371Z  INFO server: Using uws websocket server (event=INFO)
10:36:39.376Z  INFO server: Listening for tcp connections on 0.0.0.0:6021 (event=INFO)
10:36:39.377Z  INFO server: Listening for browser connections on 0.0.0.0:6020 (event=INFO)
10:36:39.377Z  INFO server: Deepstream started (event=INFO)
10:36:45.617Z  INFO server: from 127.0.0.1:64223 via tcp (event=INCOMING_CONNECTION)
10:36:45.622Z DEBUG server: 127.0.0.1:64223: AREQ{} (event=AUTH_ATTEMPT)
10:36:45.623Z  INFO server: OPEN (event=AUTH_SUCCESSFUL)
cache.set { key: 'file/ciqkr6alk000177vicg0fnycu',
  value: '{"_v":0,"_d":{}}' }
cache.set { key: 'file/ciqkr6alk000177vicg0fnycu',
  value: { _v: 0 },
  entry: { __ds: { _v: 0 } } }
10:37:41.295Z DEBUG server: for R:file/ciqkr6alk000177vicg0fnycu by OPEN (event=S)
10:37:41.329Z  INFO server: OPEN (event=CLIENT_DISCONNECTED)
10:37:41.329Z DEBUG server: for R:file/ciqkr6alk000177vicg0fnycu by OPEN (event=US)
```
Here is the client log:

```
10:36:45.620Z  INFO file: Deepstream Connection State Changed. (connectionState=AWAITING_CONNECTION)
10:36:45.621Z  INFO file: Deepstream Connection State Changed. (connectionState=AWAITING_AUTHENTICATION)
10:36:45.621Z  INFO file: Deepstream Connection State Changed. (connectionState=AUTHENTICATING)
10:36:45.623Z  INFO file: Deepstream Connection State Changed. (connectionState=OPEN)
_$onMessage { raw: 'R\u001fA\u001fS\u001ffile/ciqkr6alk000177vicg0fnycu',
  topic: 'R',
  action: 'A',
  data: [ 'S', 'file/ciqkr6alk000177vicg0fnycu' ] }
_$onMessage { raw: 'R\u001fR\u001ffile/ciqkr6alk000177vicg0fnycu\u001f0\u001f',
  topic: 'R',
  action: 'R',
  data: [ 'file/ciqkr6alk000177vicg0fnycu', '0', '' ] }
undefined:1



SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Record._onRead (/Users/ronagy/Projects/GitHub/nxtedition/nxt-file/node_modules/deepstream.io-client-js/src/record/record.js:438:21)
    at Record._$onMessage (/Users/ronagy/Projects/GitHub/nxtedition/nxt-file/node_modules/deepstream.io-client-js/src/record/record.js:290:9)
    at RecordHandler._$handle (/Users/ronagy/Projects/GitHub/nxtedition/nxt-file/node_modules/deepstream.io-client-js/src/record/record-handler.js:228:25)
    at Client._$onMessage (/Users/ronagy/Projects/GitHub/nxtedition/nxt-file/node_modules/deepstream.io-client-js/src/client.js:128:42)
    at Connection._onMessage (/Users/ronagy/Projects/GitHub/nxtedition/nxt-file/node_modules/deepstream.io-client-js/src/message/connection.js:322:17)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at TcpConnection._onData (/Users/ronagy/Projects/GitHub/nxtedition/nxt-file/node_modules/deepstream.io-client-js/src/tcp/tcp-connection.js:180:7)
    at emitOne (events.js:96:13)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by ronag** [comment]
@yasserf: Where is the message spec on the new website? I can't find it.

**Comment by ronag** [comment]
More logging on the server:

```
getMsg [ 'C', 'A' ]
10:47:02.570Z DEBUG server: 127.0.0.1:49455: AREQ{} (event=AUTH_ATTEMPT)
getMsg [ 'A', 'A' ]
10:47:02.571Z  INFO server: OPEN (event=AUTH_SUCCESSFUL)
process RCRfile/ciqkriete0001j0vis468hpo9
cache.set { key: 'file/ciqkriete0001j0vis468hpo9',
  value: '{"_v":0,"_d":{}}' }
cache.set { key: 'file/ciqkriete0001j0vis468hpo9',
  value: { _v: 0 },
  entry: { __ds: { _v: 0 } } }
10:47:06.634Z DEBUG server: for R:file/ciqkriete0001j0vis468hpo9 by OPEN (event=S)
getMsg [ 'R', 'A', 'S', 'file/ciqkriete0001j0vis468hpo9' ]
_sendRecord { recordName: 'file/ciqkriete0001j0vis468hpo9',
  record: { _v: 0 } }
getMsg [ 'R', 'R', 'file/ciqkriete0001j0vis468hpo9', 0, undefined ]
10:47:06.654Z  INFO server: OPEN (event=CLIENT_DISCONNECTED)
10:47:06.654Z DEBUG server: for R:file/ciqkriete0001j0vis468hpo9 by OPEN (event=US)
```

Somehow a created record ends up as `{ _v: 0 }`. Is that correct?

```getMsg [ 'R', 'R', 'file/ciqkriete0001j0vis468hpo9', 0, undefined ]```

Looks wrong though

**Comment by ronag** [comment]
@yasserf: It's a bug in the rethinkdb connector: https://github.com/deepstreamIO/deepstream.io-storage-rethinkdb/issues/8
