### ISSUE TITLE
_onMesssage of undefined

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#201]
```javascript
  1) TypeError: Cannot read property '_$onMessage' of undefined
    at UnsubscriptionError.Error (native)
    at new UnsubscriptionError (/node_modules/rxjs/util/UnsubscriptionError.js:16:25)
    at InnerSubscriber.Subscription.unsubscribe (/node_modules/rxjs/Subscription.js:79:19)
    at InnerSubscriber.Subscriber.unsubscribe (/node_modules/rxjs/Subscriber.js:122:38)
    at InnerSubscriber._complete (/node_modules/rxjs/InnerSubscriber.js:31:14)
    at InnerSubscriber.Subscriber.complete (/node_modules/rxjs/Subscriber.js:114:18)
    at TimeoutSubscriber._complete (/node_modules/rxjs/operator/timeout.js:94:26)
    at TimeoutSubscriber.Subscriber.complete (/node_modules/rxjs/Subscriber.js:114:18)
    at TakeWhileSubscriber.nextOrComplete (/node_modules/rxjs/operator/takeWhile.js:87:25)
    at TakeWhileSubscriber._next (/node_modules/rxjs/operator/takeWhile.js:79:14)
```

client v.1.0.2

Happens when calling `discard`  on a record:

```javascript
  observe (recordName) {
    const ds = this
    const rec = ds.record.getRecord(recordName)
    return Observable.create(o => {
      const next = val => o.next(val)
      const error = err => o.error(err)
      rec.subscribe(next, true)
      rec.on('error', error)
      return () => {
        rec.unsubscribe(next)
        rec.off('error', error)
        rec.discard()
      }
    })
  }
```

**Comment by ronag** [comment]
If I add a timeout to the discard call:

```javascript
var onMessage = this._records[ recordName ]._$onMessage.bind( this._records[ recordName ] );
	                                           ^

TypeError: Cannot read property '_$onMessage' of undefined
    at RecordHandler._onDestroyPending (/node_modules/deepstream.io-client-js/src/record/record-handler.js:276:45)
    at Emitter.emit (/node_modules/component-emitter/index.js:134:20)
    at .<anonymous> (/node_modules/deepstream.io-client-js/src/record/record.js:240:10)
    at Record.whenReady (/node_modules/deepstream.io-client-js/src/record/record.js:275:3)
    at Record.discard (/node_modules/deepstream.io-client-js/src/record/record.js:237:7)
    at Timeout.setTimeout (utils.js:28:30)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by yasserf** [comment]
hey, can I asked why this is closed?

**Comment by ronag** [comment]
@yasserf: Duplicate discard.

```javascript
    const rec = ds.record.getRecord(recordName)
```

should be inside the `create`. Though, I am surprised that the problem wasn't catched in a different way.

**Comment by yasserf** [comment]
Ah, this is probably tied to:

https://github.com/deepstreamIO/deepstream.io-client-js/issues/77

Where we should set it to destroyed before telling the server

**Comment by ronag** [comment]
This is still a problem in 1.0.2:

```
{ connectionState: 'AWAITING_CONNECTION' } 'Deepstream Connection State Changed.'
{ connectionState: 'AWAITING_AUTHENTICATION' } 'Deepstream Connection State Changed.'
{ connectionState: 'AUTHENTICATING' } 'Deepstream Connection State Changed.'
{ connectionState: 'OPEN' } 'Deepstream Connection State Changed.'
ASD
/Users/ronagy/Projects/GitHub/scrap/ds/node_modules/deepstream.io-client-js/src/record/record-handler.js:276
	var onMessage = this._records[ recordName ]._$onMessage.bind( this._records[ recordName ] );
	                                           ^

TypeError: Cannot read property '_$onMessage' of undefined
    at RecordHandler._onDestroyPending (/Users/ronagy/Projects/GitHub/scrap/ds/node_modules/deepstream.io-client-js/src/record/record-handler.js:276:45)
    at Emitter.emit (/Users/ronagy/Projects/GitHub/scrap/ds/node_modules/component-emitter/index.js:134:20)
    at .<anonymous> (/Users/ronagy/Projects/GitHub/scrap/ds/node_modules/deepstream.io-client-js/src/record/record.js:240:10)
    at on (/Users/ronagy/Projects/GitHub/scrap/ds/node_modules/component-emitter/index.js:66:8)
    at Emitter.emit (/Users/ronagy/Projects/GitHub/scrap/ds/node_modules/component-emitter/index.js:134:20)
    at Record._setReady (/Users/ronagy/Projects/GitHub/scrap/ds/node_modules/deepstream.io-client-js/src/record/record.js:459:7)
    at Record._onRead (/Users/ronagy/Projects/GitHub/scrap/ds/node_modules/deepstream.io-client-js/src/record/record.js:443:7)
    at Record._$onMessage (/Users/ronagy/Projects/GitHub/scrap/ds/node_modules/deepstream.io-client-js/src/record/record.js:293:9)
    at RecordHandler._$handle (/Users/ronagy/Projects/GitHub/scrap/ds/node_modules/deepstream.io-client-js/src/record/record-handler.js:228:25)
    at Client._$onMessage (/Users/ronagy/Projects/GitHub/scrap/ds/node_modules/deepstream.io-client-js/src/client.js:128:42)
```

```javascript
var deepstream = require('deepstream.io-client-js')

var ds = deepstream(`localhost:6021`)
  .login({}, (success, authData) => {
    if (!success) {
      console.error({ authData }, 'Deepstream Authentication Failed. Shutting down...')
      setTimeout(() => process.exit(1), 500)
    }

    main()
  })

ds.on('connectionStateChanged', connectionState => {
  console.log({ connectionState }, 'Deepstream Connection State Changed.')
})

ds.on('error', (error, event, topic) => {
  console.error({ error, event, topic }, 'Deepstream Error.')
})

function main () {
  for (let i = 0; i < 512; ++i) {
    var rec = ds.record.getRecord('tmp/' + i)
    setTimeout(() => rec.discard(), 400)
  }
  console.log('ASD')
}
```

**Comment by ronag** [comment]
Actually there is a bug in my reproducible case which causes the same record to be discarded due to `var` hoisting. Though I think deepstream could handle that case a bit more gracefully?

**Comment by ronag** [comment]
This goes into a more general error check issue.

**Comment by ronag** [comment]
#222
