### ISSUE TITLE
Test intermittently fail

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#217]
This is a bit annoying:

```javascript
deepstream.io-client-js/src/client.js:185
       		throw new Error( errorMsg );
       		^

Error: connectionError: received message on half closed socket: RRlocalRecord1{"key":"value"}
    at Client._$onError (deepstream.io-client-js/src/client.js:185:9)
    at .<anonymous> (deepstream.io-client-js/src/message/connection.js:268:16)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

Only happens sometimes...

**Comment by ronag** [comment]
This was because I had other services running connecting against the mock server.
