### ISSUE TITLE
Backend client sometimes crash on this.emit is not a function

### ISSUE THREAD

**Issue by layanto** [deepstreamIO/deepstream.io-client-js#305]
```
C:\project\server\node_modules\deepstream.io-client-js\src\record\record-handler.js:315
                this.emit( 'error', 'Record \'' + recordName + '\' does not exists' );
                     ^

TypeError: this.emit is not a function
    at RecordHandler._onDestroyPending (C:\project\server\node_modules\deepstream.io-client-js\src\record\record-handler.js:315:8)
    at Record.Emitter.emit (C:\project\server\node_modules\component-emitter\index.js:134:20)
    at Record.<anonymous> (C:\project\server\node_modules\deepstream.io-client-js\src\record\record.js:280:8)
    at Record.whenReady (C:\project\server\node_modules\deepstream.io-client-js\src\record\record.js:297:3)
    at Record.delete (C:\project\server\node_modules\deepstream.io-client-js\src\record\record.js:279:7)
    at Search.destroy (C:\project\server\node_modules\deepstream.io-provider-search-rethinkdb\src\search.js:49:22)
    at Provider._onSubscriptionRemoved (C:\project\server\node_modules\deepstream.io-provider-search-rethinkdb\src\provider.js:242:26)
    at Provider._onSubscription (C:\project\server\node_modules\deepstream.io-provider-search-rethinkdb\src\provider.js:211:10)
    at Listener._$onMessage (C:\project\server\node_modules\deepstream.io-client-js\src\utils\listener.js:99:8)
    at RecordHandler._$handle (C:\project\server\node_modules\deepstream.io-client-js\src\record\record-handler.js:274:26)
    at Client._$onMessage (C:\project\server\node_modules\deepstream.io-client-js\src\client.js:128:42)
    at Connection._onMessage (C:\project\server\node_modules\deepstream.io-client-js\src\message\connection.js:362:17)
    at WebSocket.onMessage (C:\project\server\node_modules\ws\lib\WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (C:\project\server\node_modules\ws\lib\WebSocket.js:841:10)
```

**Comment by AlexBHarley** [comment]
@layanto could you provide a code snippet to reproduce? We'll take a look at it

**Comment by layanto** [comment]
Not a real use case but this code snippet sometimes triggers the this.emit is not a function crash

```
const deepstream = require('deepstream.io-client-js')
const ds = deepstream('127.0.0.1:6020')

ds.login({
    username: 'johndoe',
    password: 'secret'
}, function (success, data) {
    const queryString = JSON.stringify({
        table: 'user',
        query: true
    })
    list = ds.record.getList('search?' + queryString)

    list.subscribe((entries) => {
        console.log(entries)
        list.discard()
    })
})

ds.on('error', (error, event, topic) => {
    console.log(error, event, topic)
})
```
Possibly related to https://github.com/deepstreamIO/deepstream.io-provider-search-rethinkdb/issues/57 as sometimes the backend search provider crashed on https://github.com/deepstreamIO/deepstream.io-provider-search-rethinkdb/issues/57 and other times on https://github.com/deepstreamIO/deepstream.io-client-js/issues/305

**Comment by datasage** [comment]
This is a bug in the js client. Emit does not exist in record-handler, it does exist in record.js.

Being that this is a case where the record does not exist, is there some kind of global way to emit events? or is that event even necessary.

**Comment by yasserf** [comment]
@datasage good point

We use a global deepstream error handler for these kind of errors. They are mostly useful for raising issues and figuring out timing issues. In this case my guess might be a race condition between the backend deleting the record, and the front-end getting a discard ack and the delete message at the same time.

Just a hunch though, haven't looked into that issue, just fixed the emit callback not being valid
