### ISSUE TITLE
"NodeWebSocket is not a constructor" when executing node application

### ISSUE THREAD

**Issue by neurogas** [deepstreamIO/deepstream.io-client-js#357]
Hello! I was integrating deepstream in a library i am writing but i encounter the error in the console.

This is the minimum amount of code that is needed to trigger the problem:
index.js
```
var deepstream = require('deepstream.io-client-js')
const client = deepstream('localhost').login();
```

problem:
```
# node ./dist/main.js
        this._endpoint = BrowserWebSocket ? new BrowserWebSocket(this._url) : new NodeWebSocket(this._url, this._options.nodeSocketOptions);
                                                                              ^

TypeError: NodeWebSocket is not a constructor
    at Connection._createEndpoint (C:\Users\ricca\Desktop\deepstream\zap\dist\main.js:2549:72)
    at new Connection (C:\Users\ricca\Desktop\deepstream\zap\dist\main.js:2443:7)
    at new Client (C:\Users\ricca\Desktop\deepstream\zap\dist\main.js:1780:22)
    at createDeepstream (C:\Users\ricca\Desktop\deepstream\zap\dist\main.js:1997:10)
    at Object.<anonymous> (C:\Users\ricca\Desktop\deepstream\zap\dist\main.js:1739:14)
    at __webpack_require__ (C:\Users\ricca\Desktop\deepstream\zap\dist\main.js:20:30)
    at Object.<anonymous> (C:\Users\ricca\Desktop\deepstream\zap\dist\main.js:6614:18)
    at __webpack_require__ (C:\Users\ricca\Desktop\deepstream\zap\dist\main.js:20:30)
    at exports.CONNECTION_STATE (C:\Users\ricca\Desktop\deepstream\zap\dist\main.js:66:18)
    at Object.<anonymous> (C:\Users\ricca\Desktop\deepstream\zap\dist\main.js:69:10)
```

webpack.config.js
```
var path = require('path')
module.exports = {
    entry: {
        main: [path.resolve(__dirname, 'src/index.js')]
    },
    output: {
        filename: "./dist/[name].js"
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                loader: 'babel-loader',
                query: {
                    "presets": [
                        "es2015"
                    ],
                    "plugins": [
                    ],
                }
            }
        ]
    }
}
```

in compiled file i could find:
```
...
NodeWebSocket = __webpack_require__(34),
...
/* 34 */
/***/ (function(module, exports) {

/* (ignored) */

/***/ }),
...
```

Any suggestion? thank you!

**Comment by yasserf** [comment]
Can you try running this with a slightly older version of the client? I believe the last client updated the WebSocket dependency which has some backwards compatibility.

**Comment by neurogas** [comment]
Tryed with 2.1.1 and 2.1.0: same

This is the code i'm executing:
https://github.com/neurogas/deepstream-wrapper

```
npm install
webpack
node dist/main.js
```

**Comment by neurogas** [comment]
Maybe if i avoid using a browser tool to pack for node i could avoid opening stupid issues :)

**Comment by yasserf** [comment]
ASAP really. I just need to get the open PRs in. Was hoping for today but didn't find the time unfortunately, my guess is Wednesday.
