### ISSUE TITLE
react-native debugger issue

### ISSUE THREAD

**Issue by dziulius** [deepstreamIO/deepstream.io-client-js#375]
After adding deepstream.io-client-js to react-native project, react-native server crases when debugger is enabled:

```
Loading dependency graph, done.
 ERROR  Cannot read property 'unmask' of undefined
TypeError: Cannot read property 'unmask' of undefined
    at Receiver.unmask (<...>/node_modules/react-native/node_modules/ws/lib/Receiver.js:306:46)
    at Receiver.finish (<...>/node_modules/react-native/node_modules/ws/lib/Receiver.js:505:25)
    at Receiver.expectHandler (<...>/node_modules/react-native/node_modules/ws/lib/Receiver.js:493:33)
    at Receiver.add (<...>/node_modules/react-native/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (<...>/node_modules/react-native/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

Edit: it works just fine with version 2.1.1

**Comment by adamawang** [comment]
Ran into this same 'unmask' issue, once you downgrade to 2.1.1 the bufferutil dependency drops back down to v1.3.1 and fixes whatever websocket issues were happening with bufferutil@2+.
