### ISSUE TITLE
Crash with "UNSOLICITED_MESSAGE: PEINVALID_RPC_CORRELATION_ID"

### ISSUE THREAD

**Issue by vovayartsev** [deepstreamIO/deepstream.io-client-js#387]
**Deepstream Server Environment**
Heroku (free dyno)
Code snapshot: https://github.com/vovayartsev/deepstream-UNSOLICITED_MESSAGE-issue
Add-ons: Heroku-redis, Mongolab

**RPC Provider and Consumer scripts**
Node v7.5.0 on Mac OS 10.12.5
deepstream.io-client-js   v2.2.1
yarn.lock:  https://gist.github.com/vovayartsev/bb987637ae49ef118176277e0f3a9fed . 

```
  // provider.js
const deepstream = require('deepstream.io-client-js');
const creds = {username: 'john', password: 'helloworld'};
const client = deepstream('wss://dockhero-deepstream.herokuapp.com').login(creds);

const record = client.record.getRecord('foobar');

client.rpc.provide( “3times', function( {role, num}, response ){
  console.log(`AS ${role}.... ${num}`)
  response.send( num * 3 );
});
```

```
// consumer.js
const deepstream = require('deepstream.io-client-js');
const creds = {username: 'john', password: 'helloworld'};
const client = deepstream('wss://dockhero-deepstream.herokuapp.com').login(creds);

client.rpc.make( "3times", {role: "admin", num: 3}, function( err, result ){
  console.log( result );
});
```

I launched `provider.js` in one MacOS terminal window, and was launching and terminating (with Ctrl-C) `consumer.js` in another window on the same machine. The first two RPC calls succeeded, but the 3-rd failed:

```
$ node provider.js 
AS admin.... 3
AS admin.... 3
--- You can catch all deepstream errors by subscribing to the error event ---
/Users/vovayartsev/projects/RnD/deepstream-client/node_modules/deepstream.io-client-js/dist/lib/client.js:204
    throw new Error(errorMsg);
    ^

Error: UNSOLICITED_MESSAGE: PEINVALID_RPC_CORRELATION_IDunexpected state for rpc 3times with action A (P)
    at Client._$onError (/Users/vovayartsev/projects/RnD/deepstream-client/node_modules/deepstream.io-client-js/dist/lib/client.js:204:11)
    at RpcHandler._getRpc (/Users/vovayartsev/projects/RnD/deepstream-client/node_modules/deepstream.io-client-js/dist/lib/rpc/rpc-handler.js:136:18)
    at RpcHandler._$handle (/Users/vovayartsev/projects/RnD/deepstream-client/node_modules/deepstream.io-client-js/dist/lib/rpc/rpc-handler.js:231:18)
    at Client._$onMessage (/Users/vovayartsev/projects/RnD/deepstream-client/node_modules/deepstream.io-client-js/dist/lib/client.js:147:42)
    at Connection._onMessage (/Users/vovayartsev/projects/RnD/deepstream-client/node_modules/deepstream.io-client-js/dist/lib/message/connection.js:362:20)
    at WebSocket.onMessage (/Users/vovayartsev/projects/RnD/deepstream-client/node_modules/ws/lib/EventTarget.js:103:16)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:192:7)
    at Receiver._receiver.onmessage (/Users/vovayartsev/projects/RnD/deepstream-client/node_modules/ws/lib/WebSocket.js:146:54)
    at Receiver.dataMessage (/Users/vovayartsev/projects/RnD/deepstream-client/node_modules/ws/lib/Receiver.js:389:14)
```

There was nothing suspicious in the server logs.

**Comment by WolframHempel** [comment]
Hi @vovayartsev, UNSOLICITED_MESSAGE errors might be an indication of some race condition or faulty setup, but are generally considered an INFO rather than an error. As the error message itself suggests you can (and should) capture them all by subscribing to your client's `error` event, e.g.
```
ds.on( 'error', error => {});
```
which will handle them gracefully and prevents the server from crashing. The client will report anything from mild warnings to major errors using the error event, so this might happen from time to time.

**Comment by vovayartsev** [comment]
Hi @WolframHempel .   Got it, thanks. This sounds fine as long as it prevents the JS script from crashing.
