### ISSUE TITLE
connectionError

### ISSUE THREAD

**Issue by sabbir-hossain** [deepstreamIO/deepstream.io-client-js#482]
I have my own `deepstream` server which is connected on `wss://localhost:6020` (using `certs` for `wss`). When I try to connect deepstream server from node-server, I'm getting following error:

```
--- You can catch all deepstream errors by subscribing to the error event ---

/Users/sabbir/project/common/node_modules/deepstream.io-client-js/dist/lib/client.js:204
    throw new Error(errorMsg);
          ^
Error: connectionError: {"type":"error","target":{"_events":{},"_eventsCount":0,"readyState":3,"bytesReceived":0,"extensions":null,"protocol":"","_binaryType":"nodebuffer","_closeFrameReceived":false,"_closeFrameSent":false,"_closeMessage":"","_closeTimer":null,"_finalized":true,"_closeCode":1006,"_receiver":null,"_sender":null,"_socket":null,"_ultron":null,"protocolVersion":13,"_isServer":false,"url":"wss://localhost:6020/deepstream","_req":null}} (C)
    at Client._$onError (/Users/sabbir/project/common/node_modules/deepstream.io-client-js/dist/lib/client.js:204:11)
    at Timeout._onTimeout (/Users/sabbir/project/common/node_modules/deepstream.io-client-js/dist/lib/message/connection.js:319:19)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[nodemon] app crashed - waiting for file changes before starting...
```

How can I fix this bug? Thanks in advance.

**Comment by yasserf** [comment]
You using V4? Appears to be a binary stream.

**Comment by sabbir-hossain** [comment]
@yasserf 

```
"deepstream.io-client-js": "^2.3.0"
```
**Deepstream.io version**
```
  "version": "3.1.5"
```

**Comment by yasserf** [comment]
Can you elaborate more? It appears you having a node buffer which means its probably binary, which version 3 doesn't have.

**Comment by yasserf** [comment]
Closing due to inactivity, feel free to open if it's still an issue!
