### ISSUE TITLE
TypeError: buff.readUIntBE is not a function after client.record.getRecord(recordPath);

### ISSUE THREAD

**Issue by delusionxb** [deepstreamIO/deepstream.io-client-js#490]
code like const record = this.client.record.getRecord(recordPath); gives me following error:

```
/Users/frank/git-projects/charon/node_modules/@deepstream/client/dist/binary-protocol/src/message-parser.js:94
    var metaLength = buff.readUIntBE(offset + 2, 3);
                          ^

TypeError: buff.readUIntBE is not a function
    at readBinary (/Users/frank/git-projects/charon/node_modules/@deepstream/client/dist/binary-protocol/src/message-parser.js:94:27)
    at _loop_1 (/Users/frank/git-projects/charon/node_modules/@deepstream/client/dist/binary-protocol/src/message-parser.js:30:18)
    at Object.parse (/Users/frank/git-projects/charon/node_modules/@deepstream/client/dist/binary-protocol/src/message-parser.js:63:23)
    at WebSocket.socket.onmessage (/Users/frank/git-projects/charon/node_modules/@deepstream/client/dist/src/connection/socket-factory.js:21:45)
    at WebSocket.onMessage (/Users/frank/git-projects/charon/node_modules/@deepstream/client/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (/Users/frank/git-projects/charon/node_modules/@deepstream/client/node_modules/ws/lib/websocket.js:796:20)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
```

**Comment by yasserf** [comment]
Hey, can you provide a bit more detail? Which server version are you using?

**Comment by delusionxb** [comment]
I'm using deepstream docker image, and without any further configuration
```
docker pull deepstreamio/deepstream.io
Using default tag: latest
latest: Pulling from deepstreamio/deepstream.io
Digest: sha256:37da95c3f681bd013a2120528906a7bd473782b4fcec7d6c01c0d8e80d8a0eb1
Status: Image is up to date for deepstreamio/deepstream.io:latest
```

The client version is @deepstream/client@4.0.0-rc.28

**Comment by yasserf** [comment]
Yeah you’ll need to use docker image 4.0.0 as latest is still v3

**Comment by delusionxb** [comment]
OK, thanks, then it's NOT a bug, close it

**Comment by yasserf** [comment]
You can start using it now, we are adding a few small new features under the 4.0.0 release but the reason we haven't yet announced it is because I'm looking to get the deepstream.io site better and also try sort out some of the typings and such. Any contributions to the documentation would be welcome! :$
