### ISSUE TITLE
"TypeError: Cannot read property 'toString' of undefined" when client.record.getRecord()

### ISSUE THREAD

**Issue by delusionxb** [deepstreamIO/deepstream.io-client-js#494]
I'm using deepstream docker image to start server, without any configuration
```
docker run -d --name dpContainer -p '6020:6020' -p '8080:8080' deepstreamio/deepstream.io:4.0.0
```
docker image:
```
docker inspect deepstreamio/deepstream.io:4.0.0
{
        "Id": "sha256:bf28411d9c1cf95d6a3b884b097a06e93b895771117715f8af13b019d68da282",
        "RepoTags": [
            "deepstreamio/deepstream.io:4.0.0"
        ],
        "RepoDigests": [
            "deepstreamio/deepstream.io@sha256:559793015051c49c086fde63eff15bfeae36217d2f9e89eda8bfe6cc6ecf796b"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2019-06-14T12:39:24.750956Z",
    ......
}
```

I'm using node 10.16.0 and running example code from https://deepstream.io/docs/client-js/datasync-client-record/index.html
```
const deepstream = require('@deepstream/client')
const client = deepstream( 'localhost:6020')
client.login()
// this will cause error in container
const record = client.record.getRecord('user/johndoe')
```

client version:
"@deepstream/client": "^4.0.0-rc.30"

docker logs dpContainer
```
Debugger listening on ws://0.0.0.0:9229/209a6cab-9f4a-4d17-8917-1f98b7a24b8a
For help, see: https://nodejs.org/en/docs/inspector
      _                     _
   __| | ___  ___ _ __  ___| |_ _ __ ___  __ _ _ __ ____
  / _` |/ _ \/ _ \ '_ \/ __| __| '__/ _ \/ _` | '_ ` _  \
 | (_| |  __/  __/ |_) \__ \ |_| | |  __/ (_| | | | | | |
  \__,_|\___|\___| .__/|___/\__|_|  \___|\__,_|_| |_| |_|
                 |_|
 =====================   starting   =====================
INFO | logger ready: std out/err
INFO | server name: jx4h0wb4-gas8fpbngbs0
INFO | deepstream version: 4.0.0-rc.10
INFO | configuration file loaded from conf/config.yml
INFO | authenticationHandler ready: none
INFO | permissionHandler ready: none
INFO | cache ready: local cache
INFO | storage ready: noop storage
INFO | monitoring ready: noop monitoring
INFO | Listening for websocket connections on 0.0.0.0:6020/deepstream
INFO | Listening for health checks on path /health-check
INFO | connectionEndpoint ready: µWebSocket Connection Endpoint
INFO | Listening for http connections on 0.0.0.0:8080
INFO | Listening for health checks on path /health-check
INFO | connectionEndpoint ready: HTTP connection endpoint
INFO | Deepstream started
INCOMING_CONNECTION | from  (172.17.0.1)
AUTH_SUCCESSFUL | open
TypeError: Cannot read property 'toString' of undefined
    at MessageProcessor.onPermissionResponse (/src/message/message-processor.ts:66:94)
    at OpenPermissionHandler.canPerformAction (/src/permission/open-permission-handler.ts:23:5)
    at MessageProcessor.process (/src/message/message-processor.ts:44:39)
    at UwsSocketWrapper.socketWrapper.onMessage (/src/message/websocket/connection-endpoint.ts:334:12)
    at message (/src/message/uws/connection-endpoint.ts:72:34)
```

**Comment by yasserf** [comment]
hey! I pushed a new version.

This issue is because I'm doing some pretty hefty refactoring to get monitoring and clustering and as such I accidentally committed incorrect default values for permissions. I fixed the issue but if you want to use Valve you'll need to update config.yml (or just let me know on this issue).

Thanks for raising!
